import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the user slice
const initialState = {
  isLogin: false, // Indicates if a user is logged in (initially false)
  user: {}, // Stores user data (initially an empty object)
};

// Create a userSlice using createSlice
export const userSlice = createSlice({
  name: "user", // The name of the slice
  initialState, // The initial state for the slice
  reducers: {
    // Define reducer functions
    login: (state, action) => {
      // Reducer for handling login action
      state.isLogin = true; // Set isLogin to true when the user logs in
      state.user = action.payload; // Store user data from the action payload
    },
    signUp: (state, action) => {
      // Reducer for handling sign-up action
      state.isLogin = true; // Set isLogin to true when the user signs up
      state.user = action.payload; // Store user data from the action payload
    },
    logOut: (state, action) => {
      // Reducer for handling logout action
      state.isLogin = false; // Set isLogin to false when the user logs out
      state.user = null; // Clear user data by setting it to null
    },
  },
});

// Export action creators generated by createSlice
export const { login, signUp, logOut } = userSlice.actions;

// Export the reducer function generated by createSlice
export default userSlice.reducer;
